package types

type CONTACT_TYPE string

const (
	CONTACT_TYPE_EMAIL CONTACT_TYPE = "EMAIL"
	CONTACT_TYPE_PHONE CONTACT_TYPE = "PHONE"
)

type USER_STATUS string

const (
	PENDING USER_STATUS = "PENDING"
	ACTIVE  USER_STATUS = "ACTIVE"
	REJECT  USER_STATUS = "REJECT"
	BANNED  USER_STATUS = "CLOSED"
)

type LANGUAGE string

const (
	LANGUAGE_EN LANGUAGE = "EN"
	LANGUAGE_ID LANGUAGE = "ID"
)
